const { addPropertyInterest } = require("../controllers/contact/contact");

const contactFields = [
    {
        "name": "firstName",
        "label": "First Name",
        "type": "text",
        "fixed": true,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [
            {
                "require": true,
                "message": "First Name is required.",
            },
        ],
    },
    {
        "name": "lastName",
        "label": "Last Name",
        "type": "text",
        "fixed": true,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [
            {
                "require": true,
                "message": "Last Name is required.",
            },
        ],
    },
    {
        "name": "title",
        "label": "Title",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "email",
        "label": "Email",
        "type": "email",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [
            {
                "require": true,
                "message": "Email is required.",
            },
            {
                "type": "email",
                "message": "Invalid email format.",
            },
        ],
    },
    {
        "name": "phoneNumber",
        "label": "Phone Number",
        "type": "tel",
        "fixed": true,
        "delete": false,
        "belongsTo": null,
        "backendType": "Number",
        "isTableField": true,
        "options":[],
        "validation": [
            {
                "require": true,
                "message": "",
            },
        ],
    },
    {
        "name": "mobileNumber",
        "label": "Mobile Number",
        "type": "tel",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "Number",
        "isTableField": true,
        "validation": [
            {
                "require": false,
                "message": "",
            },
        ],
    },
    {
        "name": "physicalAddress",
        "label": "Physical Address",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "mailingAddress",
        "label": "Mailing Address",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "preferredContactMethod",
        "label": "Preferred Contact Method",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "leadSource",
        "label": "Lead Source",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "referralSource",
        "label": "Referral Source",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "campaignSource",
        "label": "Campaign Source",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "leadStatus",
        "label": "Lead Status",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "options": [
            {
                "name": "active",
                "value": "active",
            },
            {
                "name": "pending",
                "value": "pending",
            },
            {
                "name": "sold",
                "value": "sold",
            }
        ],
        "validation": [],
    },
    {
        "name": "leadRating",
        "label": "Lead Rating",
        "type": "number",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "Number",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "leadConversionProbability",
        "label": "Lead Conversion Probability",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
  
    {
        "name": "notesandComments",
        "label": "Notes and Comments",
        "type": "textarea",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": false,
        "validation": [],
    },
    {
        "name": "tagsOrLabelsForcategorizingcontacts",
        "label": "Tags or Labels",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "birthday",
        "label": "Birthday",
        "type": "date",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "Date",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "anniversary",
        "label": "Anniversary",
        "type": "date",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "Date",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "keyMilestones",
        "label": "Key Milestones",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "dob",
        "label": "Date of Birth",
        "type": "date",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "gender",
        "label": "Gender",
        "type": "select",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "options": [
            {
                "name": "Male",
                "value": "male",
            },
            {
                "name": "Female",
                "value": "female",
            }
        ], // Possible gender options
        "validation": [],
    },
    {
        "name": "occupation",
        "label": "Occupation",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "interestsOrHobbies",
        "label": "Interests or Hobbies",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "communicationFrequency",
        "label": "Communication Frequency",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "preferences",
        "label": "Preferences",
        "type": "textarea",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": false,
        "validation": [],
    },
    {
        "name": "linkedInProfile",
        "label": "LinkedIn Profile URL",
        "type": "url",
        "fixed": true,
        "delete": false,
        "belongsTo": null,
        "backendType": "Mixed",
        "isTableField": false,
        "validation": [
            {
                "message": "Invalid type value for LinkedIn Profile URL",
                "formikType": "url",
            }
         ],
    },
    {
        "name": "facebookProfile",
        "label": "Facebook Profile",
        "type": "url",
        "fixed": true,
        "delete": false,
        "belongsTo": null,
        "backendType": "Mixed",
        "isTableField": false,
        "validation": [
            {
                "formikType": "url",
                "message": "Invalid type value for facebook",            },
        ],
    },
    {
        "name": "twitterHandle",
        "label": "Twitter Username",
        "type": "url",
        "fixed": true,
        "delete": false,
        "belongsTo": null,
        "backendType": "Mixed",
        "isTableField": false,
        "validation": [
            {
             "message": "Invalid type value for Twitter Username",
             "formikType": "url",
            }
        ],
   },
    {
        "name": "otherProfiles",
        "label": "Other Social Media Profiles URL",
        "type": "url",
        "fixed": true,
        "delete": false,
        "belongsTo": null,
        "backendType": "Mixed",
        "isTableField": false,
        "validation": [
            {
                "message": "Invalid type value for Other Social Media Profiles URL",
                "formikType": "url",
            }
        ],
    },
    {
        "name": "agentOrTeamMember",
        "label": "Agent or Team Member",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "internalNotesOrComments",
        "label": "Internal Notes or Comments",
        "type": "textarea",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": false,
        "validation": [],
    },
    
   
];

exports.contactFields = contactFields;
