const propertiesFields = [
    {
        "name": "name",
        "label": "Name",
        "type": "text",
        "fixed": true,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "editable": false,
        "isTableField": true,
        "options": [],
        "validation": [
            {
                "require": true,
                "message": "",
            },
        ],
    },
    {
        "name": "propertyType",
        "label": "Property Type",
        "type": "text",
        "fixed": true,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "propertyAddress",
        "label": "Property Address",
        "type": "text",
        "fixed": true,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "listingPrice",
        "label": "Listing Price",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "squareFootage",
        "label": "Square Footage",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "numberofBedrooms",
        "label": "Number of Bedrooms",
        "type": "number",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "Number",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "numberofBathrooms",
        "label": "Number of Bathrooms",
        "type": "number",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "Number",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "yearBuilt",
        "label": "Year Built",
        "type": "number",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "Number",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "propertyDescription",
        "label": "Property Description",
        "type": "textarea",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": false,
        "validation": [],
    },
    {
        "name": "lotSize",
        "label": "Lot Size",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "parkingAvailability",
        "label": "Parking Availability",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "appliancesIncluded",
        "label": "Appliances Included",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": false,
        "validation": [],
    },
    {
        "name": "heatingAndCoolingSystems",
        "label": "Heating and Cooling Systems",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": false,
        "validation": [],
    },
    {
        "name": "flooringType",
        "label": "Flooring Type",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": false,
        "validation": [],
    },
    {
        "name": "exteriorFeatures",
        "label": "Exterior Features",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": false,
        "validation": [],
    },
    {
        "name": "communityAmenities",
        "label": "Community Amenities",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": false,
        "validation": [],
    },
    {
        "name": "propertyPhotos",
        "label": "Property Photos",
        "type": "file",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "Array",
        "isTableField": false,
        "validation": [],
    },
    {
        "name": "virtualToursOrVideos",
        "label": "Virtual Tours or Videos",
        "type": "file",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "Array",
        "isTableField": false,
        "validation": [],
    },
    {
        "name": "floorPlans",
        "label": "Floor Plans",
        "type": "file",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "Array",
        "isTableField": false,
        "validation": [],
    },
    {
        "name": "propertyDocuments",
        "label": "Property Documents",
        "type": "file",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "Array",
        "isTableField": false,
        "validation": [],
    },
    {
        "name": "listingStatus",
        "label": "Listing Status",
        "type": "select",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "options": [
            { "name": "Active", "value": "active" },
            { "name": "Pending", "value": "pending" },
            { "name": "Sold", "value": "sold" }
        ],
        "validation": [],
    },
    {
        "name": "listingAgentOrTeam",
        "label": "Listing Agent or Team",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "listingDate",
        "label": "Listing Date",
        "type": "date",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "marketingDescription",
        "label": "Marketing Description",
        "type": "textarea",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": false,
        "validation": [],
    },
    {
        "name": "multipleListingService",
        "label": "Multiple Listing Service",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": false,
        "validation": [],
    },
    {
        "name": "previousOwners",
        "label": "Previous Owners",
        "type": "number",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "Number",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "purchaseHistory",
        "label": "Purchase History",
        "type": "textarea",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": false,
        "validation": [],
    },
    {
        "name": "propertyTaxes",
        "label": "Property Taxes",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "homeownersAssociation",
        "label": "Homeowners Association",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "mortgageInformation",
        "label": "Mortgage Information",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "sellers",
        "label": "Sellers",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "buyers",
        "label": "Buyers",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "propertyManagers",
        "label": "Property Managers",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "contractorsOrServiceProviders",
        "label": "Contractors or Service Providers",
        "type": "text",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": true,
        "validation": [],
    },
    {
        "name": "internalNotesOrComments",
        "label": "Internal Notes or Comments",
        "type": "textarea",
        "fixed": false,
        "delete": false,
        "belongsTo": null,
        "backendType": "String",
        "isTableField": false,
        "validation": [],
    }
];

exports.propertiesFields = propertiesFields;
